### ISSUE TITLE
I have question on error case

### ISSUE THREAD

**Issue by sovernut** [Gael-Lopes-Da-Silva/YellowedVSCode#2]
Hi I have question for highlighting error in this theme
Is there anything that indicate line error ?

I use Golang when declare unused var its not highlighting that line

![image](https://github.com/Gael-Lopes-Da-Silva/Yellowed/assets/24727437/a105fc15-92fe-46fd-b9ec-4371de72a1a3)

**Comment by Gael-Lopes-Da-Silva** [comment]
Hello, thank you to send me this issue.

By the indication of line error, are you talking about the underlines below errors find by the linter? If that is the case then it's deliberately disabled because I found it much better to use an extension like Error Lens to see errors. If that is not the case, then can you give me a more detailed explanation?

I'm sorry if I cannot explain myself or understand properly, since I'm not a native english speaker.

**Comment by sovernut** [comment]
Ok i got it it the case that you pointed.
I have download Error Lens and its working fines,
Thank for explanation anyway!
